### DISCUSSION TITLE
Post list doesn't show up on .../posts

### DISCUSSION THREAD

**Discussion by sosunnyproject** [mmistakes/so-simple-theme#369] [Q&A] [answered]
Hello! Thanks for amazing theme for github.io blog!
I manually downloaded this repo and merged with my previous files. 
I got most of stuff done, but the list of posts don't show up on ...url../posts site.
I'm new to jekyll, so i might have missed something easy, but cannot find the error. 

I currently set up the directory as this https://github.com/sosunnyproject/sosunnyproject.github.io
My posts.md is under docs>posts.md, and blog posts are under docs>_posts>xxx.md. 
I think my _data>navigation.yml, and posts.md are written correctly. 
My _config.yml is at head directory, and part of it is: 
```yml
# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
```
Not sure if I should write my path as "/docs/_posts". 
If you could take a look, that'd be amazing!!

**Comment by mmistakes** [comment, marked as answer]
For `_posts` I've always just done front matter defaults like this:

```
defaults:
  - scope:
      path: ""
      type: posts
```

I'd encourage you to check Jekylll's official docs on front matter defaults as they explain it all more better than I could.

https://jekyllrb.com/docs/configuration/front-matter-defaults/
