### ISSUE TITLE
How to add image from url?

### ISSUE THREAD

**Issue by carloscarcamo** [mmistakes/so-simple-theme#154]
I wonder if it possible to add image from url instead of local files

This doesn't work for me
```
image:
  feature: http//url_image.png
  credit: someone
...
```

**Comment by mmistakes** [comment]
By default images have to be in your site's images folder. You can modify the post and page layouts to use a full path to externally hosted images by editing line 16 in post.html and page.html in `_layouts/`.

**Comment by carloscarcamo** [comment]
thanks!
I have changed the layout and used a flag to know when is an external image and when local image

```
image:
  feature: http://url_img.jpg
  external: true
  credit:  someone
```
