### ISSUE TITLE
Tags are not breaking

### ISSUE THREAD

**Issue by geyslan** [mmistakes/so-simple-theme#173]
Seems like tags are not fully responsive. Could you check it?
![Image](https://drive.google.com/uc?export=download&id=0B2KIgi5sFebzYWptMzdTSEJ6T2c)

**Comment by geyslan** [comment]
The image is not showing but there are scroll bars. I think that the tag "reverse engineering" should be breaked.

**Comment by indrekots** [comment]
I can confirm this issue. On smaller screen sizes a horizontal scrollbar appears. Just a thought, since screen real estate is limited on mobile devices, maybe it would be wise to hide the list of tags?

**Comment by geyslan** [comment]
> Just a thought, since screen real estate is limited on mobile devices, maybe it would be wise to hide the list of tags?

I think it's a solution. Changing the type (css) of the tags could be another way.

**Comment by indrekots** [comment]
Another possible solution: removing the non-breaking spaces in the list of tags. But I'm guessing they were added there for a reason.

**Comment by mmistakes** [comment]
Check my latest commit to see how I fixed this. Two fairly minor things.

1. Modify tag markup in `post.html` layout to build the links as an unordered list.
2. Update `.entry-tags` CSS in `_page.scss`.

### post.html

``` html
<ul class="entry-tags">
  {% for tag in page.tags %}<li><a href="{{ site.url }}/tags/#{{ tag }}" title="Pages tagged {{ tag }}">{{ tag }}</a></li>{% endfor %}
</ul>
```

### _page.scss

``` css
.entry-tags {
	margin: 2em 0 0;
  padding: 0;
	text-transform: uppercase;
	@include font-size(16);
	font-weight: 600;
  a {
    color: $text-color;
    padding: 0 5px;
  }
  li {
    display: inline-block;
    margin-bottom: 0;
    &:before {
      content: "\2022";
    }
    &:first-child {
      &:before {
        content: "";
      }
      a {
        padding-left: 0;
      }
    }
  }
}
```

![so-simple-responsive](https://cloud.githubusercontent.com/assets/1376749/10873205/e13c87be-80de-11e5-9ac4-a921d5925173.gif)
