### ISSUE TITLE
css properties defined for code tag that are child of p tag only

### ISSUE THREAD

**Issue by qvn** [mmistakes/so-simple-theme#23]
css properties were defined for `code` tags that are child of a `p` tag. 

``` css
p code{font-size:16px;font-size:0.75rem;white-space:nowrap;margin:0 2px;padding:0 5px;border:1px solid #e6e6e6;background-color:#f2f2f2;-webkit-border-radius:3px;-moz-border-radius:3px;border-radius:3px;}
```

How about `code` tags that are child of `ul` or `li`?

Define global `code` will interfere with pygment I think.
