### ISSUE TITLE
post description not shown

### ISSUE THREAD

**Issue by kerner1000** [mmistakes/so-simple-theme#235]
Forst of all, awesome work!

But I miss the "description" text, its not shown anywhere..

e.g.
```
---
layout: post
title: "health-check external disk"
description: "Hard disk health is measured using S.M.A.R.T. (if available) and bad blocks scan."
category: Linux
---
```

**Comment by mmistakes** [comment]
The theme doesn't use `description` on posts or pages. Use `excerpt` instead.

[sample-post.md](https://github.com/mmistakes/so-simple-theme/blob/master/_posts/articles/2011-03-10-sample-post.md)

```yaml
---
layout: post
title: Sample Post
excerpt: "Just about everything you'll need to style in the theme: headings, paragraphs, blockquotes, tables, code blocks, and more."
---
```

Which will then populate a excerpt in post indexes and in the various `meta` tags in the `<head>`.
