### ISSUE TITLE
Modifying the menu

### ISSUE THREAD

**Issue by ghost** [mmistakes/so-simple-theme#237]
I like the how the menu looks when I open it up on my phone. However, what needs to be done, so that  It looks and behaves the same way when opened in a desktop browser?

**Comment by mmistakes** [comment]
You'll need to modify the CSS for the top nav partial [`_sass/navigation.scss`](https://github.com/mmistakes/so-simple-theme/blob/master/_sass/_navigation.scss).

The code is all mobile first, meaning the mobile styles come first and are modified as the breakpoints increase. If you want the mobile styles to apply to desktop just remove the `@include media($medium)` styles found in most of the declarations.

Those are currently being used to override the mobile styles. For example

```scss
#nav-toggle {
  z-index: 20;
  display: block;
  vertical-align: top;
  margin: 0;
  padding: 6px 20px;
  background-color: $black;
  height: 44px;
  @include rounded(0);

  @include media($medium) {
    display: none;
  }
}
```

styles the "menu button" and on 768px and up (`$medium)` it's hidden with `display: none`.
