### ISSUE TITLE
Single entry for site.author.links does not work

### ISSUE THREAD

**Issue by v60fan** [mmistakes/so-simple-theme#280]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [x] I believe this to be a bug with the theme.
  - [x] I am using the latest version of the theme.
  - [x] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment information

- **So Simple version: 3.1.0** 
- **Jekyll version: 3.7.3**
- **GitHub Pages hosted site: no**
- **Operating system(s): linux with docker**

---

## Expected behavior

I'm wanting to only list a single entry in site.author.links (in my case Instagram). However, when I only have this single entry, nothing appears in the sidebar under the author. If I simply add a second link, such as GitHub, the first link appears. Is it not possible to only have 1 link entry?

## Steps to reproduce the behavior

Here is the excerpt in my _config.yml
```
author:
  name: My Name
  picture: /images/my_image.jpg
  email:
  twitter:
  links:
    - title: Instagram
      url: https://instagram.com/my_profile
      icon: fab fa-instagram
```
